services:
  postgres:
    image: postgis/postgis
    networks:
      - siamo-api
    environment:
      POSTGRES_DB: siamois
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_2:/data/postgres

  siamois:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - siamo-api
    environment:
      SIAMOIS_PORT: 8099
      DEFAULT_LANG: fr
      SIAMOIS_DOCUMENTS_PATH: /srv/files
      DB_URL: jdbc:postgresql://postgres:5432/siamois
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      CONTEXT_PATH:
      SIAMOIS_ADMIN_LOGIN:
      SIAMOIS_ADMIN_PASSWORD:
      SIAMOIS_ADMIN_EMAIL:
      SIAMOIS_JWT_SECRET:
      SMTP_AUTH_ENABLED:
      EMAIL_SENDER_ADDRESS:
      SMTP_HOST:
      SMTP_PORT:
      SMTP_USERNAME:
      SMTP_PASSWORD:
    ports:
      - "9012:8099"
    volumes:
      - siamois_files:/srv/files


networks:
  siamo-api:

volumes:
  postgres_data_2:
  siamois_files: